
name: main

on:
  workflow_dispatch:
  schedule:
  - cron: "*/3 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    - name: Update README.md
      run: |
        git config --global user.email "toantran014@gmail.com"
        git config --global user.name "blackbold"
        git add .
        git commit -m "Updated README.md" || echo "No changes to commit"
        git push
